version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./frontend/onco-lens/
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - "27017:27017"

    volumes:
      - ./../mydata:/data/db
  
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
  
  python-backend:
    build:
      context: ./backend/api/               # correct path from root
      dockerfile: Dockerfile
    container_name: python_backend
    ports:
      - "8001:8001"            # host:container
    volumes:
      - ./backend/api:/app             # correct path for live reload
    environment:
      - PYTHONUNBUFFERED=1

# Volumes define
volumes: 
  mydata: